# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='category_name',
        ),
    ]
