# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import lend.models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0002_auto_20170821_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(help_text='Book Cover', upload_to=lend.models.PathAndRename('covers/'), verbose_name='Book Cover'),
        ),
    ]
