# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0002_auto_20170808_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(help_text='Book Cover', upload_to=None, verbose_name='Book Cover'),
        ),
    ]
