# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0003_auto_20170821_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='book_borrowable',
            field=models.BooleanField(default=True),
        ),
    ]
