# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0004_auto_20170821_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.ManyToManyField(to='lend.Genre'),
        ),
    ]
