# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0005_auto_20170825_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_edition',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.ManyToManyField(blank=True, to='lend.Genre'),
        ),
    ]
