# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_bookrequest_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
